print("Tabela Verdade do AND:")
print(True and True and True)
print(True and False and True)
print(False and True)
print(False and False)

print("\nTabela Verdade do XOR:")
print(True ^ True)
print(True ^ False)
print(False ^ True)
print(False ^ False)

print("\nTabela Verdade do OR:")
print(True or True)
print(True or False)
print(False or True)
print(False or False)